language: generic 
sudo: required #any timee we use docker we need su privilages , so travis n  eeds it
services: 
  - docker # hey travis we need copy of travis
before_install:
  - docker build -t rapczart:udemy-sec7-docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true rapczart/udemy-sec7-docker-react npm run test -- --coverage